require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 300

Metrics/BlockLength:
  Max: 25
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'scnnr.gemspec'

Style/MethodDefParentheses:
  EnforcedStyle: require_parentheses

Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
    reduce: inject

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/Documentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

RSpec/NestedGroups:
  Max: 5
